<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/animate.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/font-awesome.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/flaticon.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/themify-icons.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/slick.css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/prettyPhoto.css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/shortcodes.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/main.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/megamenu.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/responsive.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/css/custom.css"/>